# travis build for nix
sudo: required
language: nix
script: nix-build
#install: travis_retry

cache:
  directories:
    - /nix/
    - $HOME/
#before_cache: nix-collect-garbage -d
# todo add stack build as well
cache:
    timeout: 9000
